### ISSUE TITLE
Quarkus integration 

### ISSUE THREAD

**Issue by renannprado** [casid/jte#61] opened 2021-02-22 09:22 UTC
@casid I'm creating this thread to track the integration (or example) with Quarkus as there may be more interested people in the topic.

When we're finally able to integrate, I would suggest to possibly contribute the example to this repository so that this can be part of your pipeline + showing other people how to do it.

Here's the repository where I'll be doing the tests (contributions are welcome): https://github.com/renannprado/quarkus-jte-example

It would be very nice if I could get a bit of guidance from you to be able to integrate with Quarkus, but I could also seek for help in the Quarkus community if that's necessary.

**Comment by casid** [comment] 2021-02-22 09:34
@renannprado cool, thanks!

Just a quick guess from the error message you receive. Maybe Quarkus is using its own classloader and we need to pass that to the Java Compiler. There was a similiar issue with Ktor: https://github.com/casid/jte/issues/35

**Comment by renannprado** [comment] 2021-02-28 22:11
@casid I've tried to create the `TemplateEngine` like this:

```kotlin
val templateEngine: TemplateEngine = TemplateEngine.create(
        codeResolver,
        Path.of("${workingDir}/target/jte-classes/gg/jte/generated/"),
        ContentType.Html,
        Thread.currentThread().contextClassLoader
)
```

But no luck. I get the same exception.

Do you have any ideas in mind that I could try? otherwise I can seek for help in the Quarkus community too. However I'm still not sure what are the right questions to ask.

**Comment by casid** [comment] 2021-03-01 06:39
Hmm I just cloned your repository and on Windows I get this error message:

```
2021-03-01 07:36:29,696 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test failed, error id: f0922e9a-7cbf-435a-b11e-2957c67ae3a9-1: org.jboss.resteasy.spi.UnhandledException: gg.jte.TemplateException: Failed to compile template, error at
An exception has occurred in the compiler (11.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program and the following diagnostic in your report. Thank you.
java.nio.file.InvalidPathException: Illegal char <:> at index 4: file:///C:/Users/casid/.m2/repository/io/quarkus/quarkus-core-deployment/1.11.3.Final/quarkus-core-deployment-1.11.3.Final.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at jdk.compiler/com.sun.tools.javac.file.FSInfo.getJarClassPath(FSInfo.java:112)
	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getJarClassPath(CacheFSInfo.java:93)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addJarClassPath(Locations.java:423)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFile(Locations.java:413)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:345)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:333)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:339)
	at jdk.compiler/com.sun.tools.javac.file.Locations$ClassPathLocationHandler.computePath(Locations.java:779)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SimpleLocationHandler.setPaths(Locations.java:721)
	at jdk.compiler/com.sun.tools.javac.file.Locations$ClassPathLocationHandler.lazy(Locations.java:791)
	at jdk.compiler/com.sun.tools.javac.file.Locations$ClassPathLocationHandler.getPaths(Locations.java:755)
	at jdk.compiler/com.sun.tools.javac.file.Locations.getLocation(Locations.java:2077)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getLocation(JavacFileManager.java:942)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getClassLoader(JavacFileManager.java:678)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.initProcessorLoader(JavacProcessingEnvironment.java:269)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.<init>(JavacProcessingEnvironment.java:237)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment.instance(JavacProcessingEnvironment.java:193)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.initProcessAnnotations(JavaCompiler.java:1136)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:922)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:311)
	at jdk.compiler/com.sun.tools.javac.main.Main.compile(Main.java:170)
	at jdk.compiler/com.sun.tools.javac.Main.compile(Main.java:75)
	at jdk.compiler/com.sun.tools.javac.api.JavacTool.run(JavacTool.java:208)
	at gg.jte.compiler.ClassFilesCompiler.runCompiler(ClassFilesCompiler.java:40)
	at gg.jte.compiler.ClassFilesCompiler.compile(ClassFilesCompiler.java:31)
	at gg.jte.compiler.TemplateCompiler.precompile(TemplateCompiler.java:90)
	at gg.jte.compiler.TemplateCompiler.load(TemplateCompiler.java:53)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:324)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:171)
```

This is path comes from the MANIFEST.MF Class-Path entry quarkus puts in `code-with-quarkus-dev.jar`.

**Comment by casid** [comment] 2021-03-01 07:05
I could reproduce the error you got on my Macbook :-)

I have an idea what's wrong, will post as soon as I found out more.

**Comment by renannprado** [comment] 2021-03-01 07:27
@casid I could be wrong, but I think the error in Windows is related to the `System.getProperty` call that is relying on a property that only exists in linux/mac.

That's good news! Thanks for taking a look.

**Comment by casid** [comment] 2021-03-02 05:58
No, the Windows error is a bug in the JDK compiler: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8218268

After some digging, I found this issue on Quarkus: https://github.com/quarkusio/quarkus/issues/3592

I will try two things. First, make the classpath fully configurable (currently it's only configurable for `precompile`.

Second, see if I jte can parse the classpath itself and to a better job than the JDK ;-)

If the second approach fails, we'd probably replicate some of what this class does for the Quarkus jte integration: https://github.com/quarkusio/quarkus/blob/ef55a323d52af0969c7507289c37ddcf2259da7b/core/deployment/src/main/java/io/quarkus/deployment/dev/ClassLoaderCompiler.java

**Comment by casid** [comment] 2021-03-02 17:30
I did some more digging, and this will be harder than expected!

I guess what we'll need is a quarkus extension, to integrate jte: https://quarkus.io/guides/building-my-first-extension

I will give this a try this week, implementing `io.quarkus.deployment.dev.CompilationProvider`.

**Comment by renannprado** [comment] 2021-03-03 07:48
@casid looks promising!

**Comment by casid** [comment] 2021-03-04 21:54
@renannprado I got a first very, very, very rough draft of a Quarkus extension.

But! I got a hacky DevMode test running with hot reload :-D
https://github.com/casid/quarkus-jte-example/blob/master/jte-quarkus/deployment/src/test/java/gg/jte/quarkus/test/JteQuarkusDevModeTest.java

My breakthrough was https://github.com/casid/quarkus-jte-example/blob/master/jte-quarkus/deployment/src/main/java/gg/jte/quarkus/deployment/JteCodeGenProvider.java, it allowed me to access the Quarkus runtime classpath (I'm currently storing it as system property and access it later when creating the hot reload template engine, hacky, hacky XD). If this step is executed during production we'd need to generate all template sources instead. I still don't know how to access the configuration of the jte extension from there. That'd be required to setup the template engine the exact same way for production and development.

Let me know what you think.

**Comment by casid** [comment] 2021-03-06 07:45
@renannprado I created a PR for your example repository: https://github.com/renannprado/quarkus-jte-example/pull/1

Let me know if this works on your end :-)

**Comment by renannprado** [comment] 2021-03-06 09:53
@casid thanks a lot for taking a look at it. I'll check as soon as possible. 

You mentioned dev mode, but will it be able to generate a runnable jar and native images already?

Even if not, it will be good enough to start playing with it :)

**Comment by casid** [comment] 2021-03-06 13:10
@renannprado I think the runnable jar should work. `mvn package` includes all jte classes in the runner jar. I haven't tried native images yet, would be awesome if those worked as well :-D

**Comment by renannprado** [comment] 2021-03-06 16:24
@casid both pre-compiled and non-precompiled templates worked for me. The runnable jar also worked!

The only thing that didn't work was the native image. There I got the below exception.

I'll soon merge your PR! Thanks again!

```
2021-03-06 17:22:48,738 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /test failed, error id: 4a2f5d3b-1963-4bba-9154-463019802f11-1: org.jboss.resteasy.spi.UnhandledException: gg.jte.TemplateNotFoundException: Failed to load example1.jte
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:519)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: gg.jte.TemplateNotFoundException: Failed to load example1.jte
	at gg.jte.runtime.TemplateLoader.load(TemplateLoader.java:30)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at gg.jte.TemplateEngine.resolveTemplate(TemplateEngine.java:371)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:229)
	at gg.jte.quarkus.runtime.JteTemplateRenderer.render(JteTemplateRenderer.java:21)
	at gg.jte.quarkus.runtime.JteTemplateRendererPrecompiledProvider_ProducerMethod_templateRenderer_834c801a7c0c73f86d26110e439b6abb3ef46215_ClientProxy.render(JteTemplateRendererPrecompiledProvider_ProducerMethod_templateRenderer_834c801a7c0c73f86d26110e439b6abb3ef46215_ClientProxy.zig:117)
	at org.acme.GreetingResource.hello(GreetingResource.kt:25)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 17 more
Caused by: java.lang.ClassNotFoundException: gg.jte.generated.precompiled.Jteexample1Generated
	at com.oracle.svm.core.hub.ClassForNameSupport.forName(ClassForNameSupport.java:60)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:275)
	at gg.jte.runtime.TemplateLoader.load(TemplateLoader.java:27)
	... 35 more
```

**Comment by casid** [comment] 2021-03-08 19:04
@renannprado, awesome that it works on your end!

Hmm, I suppose we need to somehow expose those classes to native code?

After a quick search I found this, which looks promising:
https://quarkus.io/guides/writing-native-applications-tips#register-reflection

Looks like we could simply add this as a build step to the extension.

**Comment by casid** [comment] 2021-03-08 21:37
I gave it a try:
https://github.com/casid/quarkus-jte-example/commit/b3882a3aa0b936b4defe1d43479977fe8a2a739a

How are you building the native image? I think I need to download and configure GraalVM first, since maven complains when I run `quarkus:native-image`.

**Comment by renannprado** [comment] 2021-03-09 14:42
@casid this is how I did.

I can't remember if it requires GraalVM or it's using docker though.

```shell
mvnw package -Pnative
```

**Comment by casid** [comment] 2021-03-10 19:26
@renannprado just tried it, it seems it does require GraalVM. I installed it and installed the native image support. Unfortunately I'm on Windows and need MSVC. This brought back dark memories from the days before Java when coding in C/C++ :-D After downloading 3GB just for MSVC Visual Studio told me to restart my PC. Seems some things never change ;-)

Will give it a try tomorrow after my PC restarted naturally...

**Comment by casid** [comment] 2021-03-10 19:39
@edward3h wow that looks pretty straight forward. I'm not sure if comparing with Quarkus helps much with native image generation. My impression so far is that Quarkus does this in a very specific, high-level way and there isn't much to reuse if one doesn't use Quarkus.

**Comment by casid** [comment] 2021-03-12 05:15
@renannprado Native image works on my end after this change: https://github.com/casid/quarkus-jte-example/commit/96edea205677c5007a5106e400c0e2a85ecfe782 👍

**Comment by renannprado** [comment] 2021-03-14 21:03
@casid I took your code and I put `master` of jte as a dependency ('cause I didn't have `1.8.1-SNAPSHOT`. Same error. 
I think I missed something.

**Comment by casid** [comment] 2021-03-14 21:14
@renannprado oh right, I just changed the jte dependency to 1.9.0

Hmm, I tested on Windows, but that shouldn't make a difference.

What I did:
- Run `mvn clean install` on jte-quarkus
- Run `mvnw package -Pnative` on the example project

**Comment by renannprado** [comment] 2021-03-14 21:28
@casid now with `1.9.0` it worked!

Thanks

**Comment by renannprado** [comment] 2021-03-22 17:15
@casid are you planning to create a real quarkus-extension out of this quest we've just went through?

**Comment by casid** [comment] 2021-03-24 04:40
@renannprado would be nice to have.. I'm a bit unsure where this should be placed. To me it looks like all official quarkus extensions are part of the quarkus repository. But I'm not sure if quarkus would like to have a jte extension on board. Did you already talk to the quarkus guys about this? Maybe you could open an issue there with a link to our demo project?

**Comment by renannprado** [comment] 2021-03-24 07:57
@casid no I haven't. But I can do this. It's minimum I can do after you put so much effort in getting it to work.
If for some reason it's not possible to put there, then I believe we should just publish the jar so that we can use it as a dependency

**Comment by renannprado** [comment] 2021-03-25 22:29
@casid I found the docs where it says how to get to the "official" extensions page of quarkus, but it might demand more commitment than you want to do.

Check it out:

https://github.com/quarkusio/quarkus/wiki/Adding-extensions-to-the-Quarkus-ecosystem#process-to-join-the-platform

I believe the quarkus extensions for jte doesn't necessarily need to be there to be useful, you might as well just publish another jar as part of this project repo (if you want). I do believe it would help to create more visibility to `jte` by doing that though.

**Comment by casid** [comment] 2021-03-27 08:26
@renannprado yeah, looking at the documentation, I'm afraid maintaining a quarkus extension is out of scope for me. I'm not using Quarkus for any of my projects (and do not plan to do so), so I'd be a very bad fit for maintaining it.

I added the help wanted label, in case some other jte user would like to transform our hacky experiment into a solid quarkus extension :-)

**Comment by renannprado** [comment] 2021-03-27 09:12
@casid It would be enough to publish a jar of it as is just so that one can use as any other dependency. Doesn't that work for you? The extension doesn't need to be part of the "official" ones until maybe it gets more attention from others and from you.
Just adding it as another module in this repo I suppose. If you don't want to do it as part of this repo, I could do it on my own just to scratch my itch, but we both know it's _your_ work. Can we find a compromise "solution"?

**Comment by casid** [comment] 2021-03-27 11:12
@renannprado sure thing, you can definitely publish that jar.

I just think it shouldn't be part of the jte repository. jte is a general purpose library. It's built in a way that let's you easily plug it into your software and configure it as you're needs see fit. This worked fine so far to integrate in all web frameworks, except Quarkus.

Quarkus is kind of the opposite of the spectrum. It's a very huge framework that enforces its ideology onto your entire project. The quarkus build process seems very complex to me and I used APIs that look like they could potentially break in the future and to be honest I would be a bit afraid to use the current extension in production, since I just don't know if it is doing the right thing for all scenarios quarkus can run. I think what would be needed here is someone very proficient in Quarkus to get the extension in production ready shape. Since Quarkus has its own template engine, I'm not sure how high their motivation would be to do that though :-)

Usually just old-school embedded Jetty & Jax-RS. For something more lightweight, Javalin is also very nice to work with.

**Comment by renannprado** [comment] 2021-03-28 19:15
@casid yeah... I can totally understand.

I'm also not sure if I'm sold to Quarkus to be honest. In the last years so many frameworks appeared, and now it's really hard decide which one to use. I've used Spring in the last ~4 years and it's ok, but its startup time is annoyingly slow.

Alright. If you agree, I would create a new repo `quarkus-jte-extension` under my github user and see where it goes. 

What do you think it's the best way to start the repository? e.g. do I copy/paste your code and commit into the new repo...? Do you want to do the first commit? The last thing I want is to do something that make it look like I did everything on my own without mentioning you.

**Comment by renannprado** [comment] 2021-07-20 22:15
@casid I didn't forget about it, it's just been a bit hard to find time to work on this.

So I've started to do something, I've already registered my group ID in Sonatype and so on...

But now I'm trying to create a simple test: https://github.com/renannprado/quarkus-jte-extension/pull/1/files#diff-efb5fd392ef0bac05e7100874533722b3058eef3879769d3c53ffc33807a3676

On top of what you have in the DevMode test... but I simply can't.

It would be nice if I get this to work because users of the lib would be writing similar tests I can imagine...
Anyhow if you have 5min and want to take a look at the PR and want to give some feedback (I've upgraded quarkus and renamed several things, but everything is almost the same).

Once I get this test to work and add a test app to the repo, then I'll build a pipeline to finally release it.

**Comment by casid** [comment] 2021-07-22 19:35
Cool, congratulations on registering with Sonatype!

I'm going to clone your repo next week and give it a shot.

**Comment by casid** [comment] 2021-07-28 04:07
@renannprado I cloned the project and looked into the test. Sorry, I have no idea what the problem is. By now, I almost forgot everything I hacked into the Quarkus extension.

**Comment by renannprado** [comment] 2021-07-28 13:39
> @renannprado I cloned the project and looked into the test. Sorry, I have no idea what the problem is. By now, I almost forgot everything I hacked into the Quarkus extension.

@casid thanks for taking a look. I'll release it without the tests then.

**Comment by renannprado** [comment] 2021-08-20 10:36
@casid it's finally released: 

https://github.com/renannprado/quarkus-jte-extension/

**Comment by casid** [comment] 2021-08-21 02:51
Hey, congratulations! I just added a link to your repository in the jte readme 👍 

Thank you for your hard work on the plugin!

I believe we can now close this issue, right?

**Closed by casid** 2021-08-21 02:51 UTC
Labels: enhancement, help wanted
