### ISSUE TITLE
WatchService slow on MacOS

### ISSUE THREAD

**Issue by roscrl** [casid/jte#122] opened 2021-11-15 22:49 UTC
Hi casid,

I was implementing a crude auto refresh on jte template change for the browser side (saving me from manually refreshing with CMD + R or F5) but found the underlying WatchService implementation within the jte DirectoryWatcher package to be slow on Mac. Below examples use [Javalin](https://javalin.io)

```java
            sse("refreshDevMode", client -> {
                DirectoryCodeResolver codeResolver = new DirectoryCodeResolver(Path.of("src", "main", "resources", "jte"));
                var watcher = new DirectoryWatcher(templateEngine, codeResolver);
                watcher.start(templates -> client.sendEvent("refresh", "Template changed, refresh browser event"));
                client.onClose(watcher::stop);
            });
```

Within script tag in a jte template (I put it in my tag/head.jte which is used across pages)

```
        const evtSource = new EventSource("refreshDevMode");
        evtSource.addEventListener("refresh", (data) => {
            console.info(data)
            location.reload()
        })
```

The above can take from 2-8 seconds it feels to detect the change and reload. See https://stackoverflow.com/questions/9588737/is-java-7-watchservice-slow-for-anyone-else + https://github.com/sbt/sbt/issues/3527.

The github issue suggests switching to https://github.com/gmethvin/directory-watcher which worked perfectly for me with pretty much instant reloads. I guess the JTE watcher could use this underneath too but is an extra dependency and may not be as big a problem for most users as the slow WatchService seems to be limited to Mac?

For completeness here is what I used instead if anyone else is needing a fast crude auto refresh implementation

```java
  sse("refreshDevMode", client -> {
                try {
                    var watcher = DirectoryWatcher.builder()
                            .path(Path.of("src", "main", "resources", "jte"))
                            .listener(event -> {
                                switch (event.eventType()) {
                                    case MODIFY -> client.sendEvent("refresh", "Template changed, refresh browser event");
                                }
                            })
                            .build();
                    watcher.watch();
                    client.onClose(() -> {
                        try {
                            watcher.close();
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    });
                } catch (IOException e) {
                    e.printStackTrace();
                }
            });
```

**Comment by casid** [comment] 2021-11-16 04:50
Hi @roscrl,

this is awesome! The extra dependency shouldn't be a problem, since jte-watcher is an optional dependency and probably only used during development. I use the watcher for a statically rendered site to regenerate html files during development and do the templating mostly on my Windows PC instead of my Macbook precicely because of this issue :-D.

I'll have a look if I can quickly include this lib into jte-watcher.

**Comment by casid** [comment] 2021-11-16 05:47
I gave it a try. The directory-watcher API is really nice and a lot faster!

Currently one CI test fails with macOS and Java 17, which I'll try to reproduce and fix on my Macbook.

**Comment by casid** [comment] 2021-11-16 20:45
Closing this :-) Feel free to reopen if there's something missing.

**Closed by casid** 2021-11-16 20:45 UTC
Labels: enhancement

**Comment by roscrl** [comment] 2021-11-16 20:46
All good, super fast JTE reloads now in action :)
