### ISSUE TITLE
Issue with application class loader

### ISSUE THREAD

**Issue by mitchdennett** [casid/jte#7] opened 2020-09-14 00:24 UTC
I'm trying to use the application class loader to load the pre compiled templates. It works when running in the IDE fine.
After building a fat jar and running that on my local Mac it works fine too.

After moving that fat jar to an ubuntu server and running it all I get is a blank screen. I also don't see anything in the logs. No errors or anything.

I'm using Java 14 both locally and on the ubuntu server.

**Comment by mitchdennett** [comment] 2020-09-14 00:35
Turns out I am not using 14 on my server. It was OpenJDK 11 on my server. 
So I compiled my jar using 14 but compiled it with a target source of 11. But that still gave me a blank screen. Is this expected?

**Comment by casid** [comment] 2020-09-14 04:54
Hey @mitchdennett,

thanks for reporting! Having no error messages is unexpected. I'd expect the class loader to complain about the wrong byte code version.

I think the problem is that I don't pass the target source version from the maven plugin to the Java compiler within jte.

Gonna look into it this evening after work!

**Comment by casid** [comment] 2020-09-14 05:57
@mitchdennett I couldn't resist to look into it before starting work :-)

I created a second maven mojo, that only generates Java files for jte templates. This will leave the entire compilation to the maven compiler plugin: https://github.com/casid/jte/commit/e070bb2a838472d38962d7772acda49609258035

I think that should fix it!

Would you like to give it a try and test if this works on your end? You'd need to clone jte, run `mvn install` and use `1.2.0-SNAPSHOT` as dependency.

I'd release `1.2.0` shortly after then :-)

**Comment by mitchdennett** [comment] 2020-09-14 11:50
@casid I can confirm it works. Thanks for responding so quick! I opened a PR to update the DOCUMENTATION.md file with the new plugin config. #8

**Comment by casid** [comment] 2020-09-14 15:29
Awesome! Thanks for confirming and also for the PR.

Gonna release 1.2.0 right now and merge #8 afterwards.

**Comment by casid** [comment] 2020-09-14 16:18
Released with `1.2.0`

**Closed by casid** 2020-09-14 16:18 UTC
Labels: bug
