### ISSUE TITLE
2.0.2 jte-maven-plugin puts compiled classes in wrong directory

### ISSUE THREAD

**Issue by bluelu** [casid/jte#152] opened 2022-05-11 21:16 UTC
Hi,

The 2.0.2 plugin version puts the compiled classes in 
"gg.jte.generated" instead in 
"gg.jte.generated.precompiled", so that the template engine won't find them.

The older version 1.12.1 works fine though.

Here is the configuration:

   
      <plugin>
        <groupId>gg.jte</groupId>
        <artifactId>jte-maven-plugin</artifactId>
        <version>2.0.2</version>
        <configuration>
          <sourceDirectory>${basedir}/src/main/jte</sourceDirectory>
          <targetDirectory>${basedir}/jte-classes</targetDirectory>
          <contentType>Html</contentType>
        </configuration>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>precompile</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

And in the application:
    <dependency>
      <groupId>gg.jte</groupId>
      <artifactId>jte</artifactId>
      <version>2.0.2</version>
    </dependency>

**Comment by casid** [comment] 2022-05-12 04:40
Welcome @bluelu.

I'm confused how this is happening. The package change to `gg.jte.generated.precompiled` is quite old. That was done in this commit a30bce3db0baf54971f0ab74414477f2316bc584, was released in version 1.8.0 and hasn't been changed since then. That's the default for `package-name` in the plugin: https://github.com/casid/jte/blob/a63a2562e9d0c105beff96febca6ed273e7f0dca/jte-maven-plugin/src/main/java/gg/jte/maven/CompilerMojo.java#L71

Can you check, if you've set the package name to a different value, when you're initializing the template engine?

**Comment by casid** [comment] 2022-05-18 12:25
Hey @bluelu, just wanted to follow up on this. Did you get it to work?

Let me know if I can provide further help.

**Comment by bluelu** [comment] 2022-05-18 19:35
Hi,

I didn't have time yet to test. I changed packageName before, but the plugin did compile them into the same folder. I will have time in about 2 weeks and will try to make a small sample project which reproduces the problem. For now though, I continue to use the old version which still works fine for me.

Sorry again for the delay

**Comment by casid** [comment] 2022-05-18 20:34
Thanks for the heads up! I'd really appreciate a sample project when you have time :-)

I'm using jte with maven on several projects and didn't run into this problem when upgrading.

**Comment by Akromangel** [comment] 2022-05-31 07:54
Version 2.0.3 also generates classes to wrong place.
```xml
            <plugin>
                <groupId>gg.jte</groupId>
                <artifactId>jte-maven-plugin</artifactId>
                <version>${jte.version}</version>
                <configuration>
                    <sourceDirectory>${project.basedir}/src/test/resources/templates</sourceDirectory>
                    <targetDirectory>target/generated-sources/jte</targetDirectory>
                    <packageName>jte.test</packageName>
                    <contentType>Plain</contentType>
                </configuration>
...
```
Classes are in `${project.baseDir}/jte-classes/jte` package name is ignored.

**Comment by casid** [comment] 2022-06-10 14:00
@bluelu, @Akromangel could you try building with version 2.0.4? Unfortunately I could not reproduce your findings, but maybe it really was the readonly annotation on those properties. At least I have no idea what else could cause this :-)

Would be awesome if you could give it a try.

**Closed** 2022-06-10 14:28 UTC
Labels: question

**Comment by casid** [comment] 2022-06-11 05:20
Thanks for the update. Glad it is working for you :-)

**Comment by Akromangel** [comment] 2022-06-12 07:30
When I have
```
<targetDirectory>target/generated-sources/jte</targetDirectory>
```
then classes are not put under target directory.

When I have
```
<targetDirectory>${project.basedir}/target/generated-sources/jte</targetDirectory>
```
then the folder is generated and classes are put there.

So it's ok with the last config value.
