### ISSUE TITLE
Type mismatch

### ISSUE THREAD

**Issue by MarkusAmshove** [casid/jte#94] opened 2021-07-14 10:26 UTC
Hi,

I currently have the same issue some other people had, where I get an exception about a mismatch in the parameters to the `render()` call.

I've used the technique to print the class loaders instances as commented in other issues, but they're all the same in my case (same object references).

I'm using precompiled templates with the Gradle plugin and get the Exceptions during JUnit tests.
Before using the Gradle plugin I had JTE version `1.5.0` and precompiled templates  which didn't result in the error.

## The error

```
jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739

Failed to render text.jte, type mismatch for parameter: Expected model.Text, got net.model.Text
gg.jte.TemplateException: Failed to render text.jte, type mismatch for parameter: Expected model.Text, got model.Text
	at gg.jte.runtime.Template.render(Template.java:43)
	at gg.jte.TemplateEngine.render(TemplateEngine.java:213)
	at template.templates.TemplateText.renderedContent(TemplateTextAo.java:26)
	at template.TemplateSollte.test01(TemplateSollte.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at gg.jte.runtime.Template.render(Template.java:36)
	... 91 more
```

**Comment by casid** [comment] 2021-07-14 18:28
Hey @MarkusAmshove, can you show me how the `TemplateEngine` is initialized?

Also, in the first line of the exception it states `Expected model.Text, got net.model.Text`. I expect this is a typo, since the message is different in the next line.

**Comment by MarkusAmshove** [comment] 2021-07-15 07:00
Yes, that was a typo, sorry :-)

I do it like this:
```java
public String render(Text model)
	{
		System.out.println("render() contextClassLoader: " + Thread.currentThread().getContextClassLoader());
		System.out.println("render() getClassLoader: " + getClass().getClassLoader());

		TemplateOutput output = new StringOutput();
		var templateEngine = TemplateEngine.createPrecompiled(ContentType.Plain);
		templateEngine.render(TEMPLATE_FILE_NAME, model, output);

		return output.toString();
	}
```

I've added the same printlns in the JUnit test, here is the output:
```
junit contextClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739
junit getClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739
render() contextClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739
render() getClassLoader: jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739
```

**Comment by casid** [comment] 2021-07-15 10:05
Hmm, that's strange. Can you show me how you generate the jte Java files? I assume you're on the latest version of jte (1.11.1)?

**Comment by MarkusAmshove** [comment] 2021-07-15 12:29
JTE: 1.11.1
Gradle Plugin: 1.11.1

I'm precompiling them with gradle, these are the two things I've added inside `build.gradle`:

```
jte {
    precompile()
}

sourceSets {
    main {
        java {
            srcDirs += file("jte-classes")
        }
    }
}
```

Note that the `sourceSets` thing does not come from the docs of JTE, but I've added it because otherwise I would get a `ClassNotFoundException`. which was essentially JTE not finding the generated classes.

**Comment by MarkusAmshove** [comment] 2021-07-15 14:10
I created a minimal repro:

https://github.com/MarkusAmshove/jte-repro

I run the code with `gradlew clean && gradlew precompileJte && gradlew build`

In the branch `master` I followed the documentation on precompiling.
Here the test fails with `ClassNotFoundException`.

In the branch `with-sourceset` I've added `jte-classes` to the java main sourceset and the `ClassNotFoundException` is gone.
However, now I get the type mismatch exception.
Note: Here I get a `ArrayIndexOutOfBoundsException` from [here](https://github.com/casid/jte/blob/master/jte-runtime/src/main/java/gg/jte/runtime/Template.java#L41), however the caught `IllegalArgumentException` is the mismatched type exception :-) (dunno why I get the out of bounds in this repro)

**Comment by casid** [comment] 2021-07-15 16:39
Thanks for providing an example repository. When I run those gradle commands, I receive a different error:

```
LibraryTest > testSomeLibraryMethod() FAILED
    gg.jte.TemplateNotFoundException at LibraryTest.java:12
        Caused by: java.lang.ClassNotFoundException at LibraryTest.java:12

1 test completed, 1 failed
```

That's because jte expects the generated Java templates on the classpath, but in the sample project they are located in `jte-classes`.

That was fixed by:
`var templateEngine = TemplateEngine.createPrecompiled(Path.of("jte-classes"), ContentType.Plain);`

Now I could reproduce your error. The error message here is super misleading. Problem was that precompile generates templates with `ContentType.Html`, but here templates are loaded as `ContentType.Plain`. So if you adjust it like this, it should work as expected:

`var templateEngine = TemplateEngine.createPrecompiled(Path.of("jte-classes"), ContentType.Html);`

I'll look into it and will provide a better error message in case this happens.

**Comment by MarkusAmshove** [comment] 2021-07-15 17:44
Oh okay, I didn't think about passing the path and thought it was "default" when I use a build tool plugin. Might be worth to put it in the documentation, because [at the bottom](https://github.com/casid/jte/blob/master/DOCUMENTATION.md#gradle) in the example it doesn't have the path :-)

I resolved this issue with adding `jte-classes` to the main sourceset (in the repro repository in the `with-sourceset` branch), but I think I like your approach better. One benefit of adding it to the sourceset is to see compile errors in the IDE (if you don't use the IntelliJ plugin or use a different IDE) instead of the precompile phase.

**Comment by casid** [comment] 2021-07-15 18:18
Ahh, sorry that part was missing in your example project and I didn't look closely into the build.gradle:

```
sourceSets {
    main {
        java {
            srcDirs += file("jte-classes")
        }
    }
}
```

After adding this snippet, the sample repo works as expected, with just this adjustment:

`var templateEngine = TemplateEngine.createPrecompiled(ContentType.Html);`

I'd definitely recommend to use the IntelliJ plugin though, otherwise writing templates isn't a lot of fun :-)

Also, the hot reload feature is very sweet for fast development without restarting the server.

**Closed by casid** 2021-07-15 18:18 UTC
