### ISSUE TITLE
unsafe produces blank

### ISSUE THREAD

**Issue by schowave** [casid/jte#203] opened 2023-03-08 10:02 UTC
When I want to use the unsafe feature like this:

```
@param myAttributeData: String

<my-component myattribute="$unsafe{myAttributeData}">TextABC</my-component>
```

I get a blank between the first '"' and the actual data. As this is a json object, it is not possible to parse that in my frontend component. Is this a bug, or does there exist a workaround?

The component in the dom looks like this and this is not valid because of the blank:
`<my-component myattribute="[{" event_category":"site_variation"}]">TextABC</my-component>`

Thanks for your help!

**Comment by kelunik** [comment] 2023-03-08 15:33
I don't see how this space _within_ your content is produced by JTE. Are you sure your data is generated properly and does not already contain this space? Why do you use `unsafe` at all there?

**Comment by casid** [comment] 2023-03-08 15:40
@schowave is this maybe a display issue when you inspect the HTML in the browser?

My guess is that the attribute string is closed after `[{"` and the remainder is invalid HTML. `unsafe` is not aware of the attribute and simply puts out the string as is. Have you tried not using unsafe as @kelunik suggested? Then, the `"` withing the JSON should be properly output-escaped.

**Comment by casid** [comment] 2023-03-24 07:14
Closing this now, since we could not reproduce the issue. @schowave in case we overlooked something, please reopen and let us know.

**Closed by casid** 2023-03-24 07:14 UTC
Labels: question

**Comment by schowave** [comment] 2023-06-26 12:31
The issue was the double quotes:

`@param myAttributeData: String

<my-component myattribute='$unsafe{myAttributeData}'>TextABC</my-component>`

produces the correct output....
